# NumPy

In [2]:
import numpy as np

## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [3]:
# Dado o seguinte array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#Selecionando apenas os impares
array[array%2==1]

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [4]:
# Dado o array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Impares = 0
np.where(arr % 2 == 1, 0, arr)


# opção professora
arr[arr%2==1] = 0
arr

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [10]:
# Importanto as 4 primeiras colunas do arquivo:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Printando as primeiras 10 colunas:
iris[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [12]:
# Considerando o arquivo do exs anterior
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Calculando a média
mu = np.mean(sepallength)
med = np.median(sepallength)
sd = np.std(sepallength)
print(mu, med, sd)

# Poderia fazer apenas em uma linha
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409
5.843333333333334 5.8 0.8253012917851409


5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [13]:
# Filtro da matriz
filtro_5 = (iris[:, 2] > 1.5) & (iris[:, 0] < 5.0)
iris[filtro_5]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

6 - Esse dataset possui nans?

In [15]:
# Verificando a existencia de nan
iris[np.isnan(iris)] # Não possui nans

array([], dtype=float64)

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [17]:
# Calculando o volume
sepal_length = iris[:, 0].astype('float')
petallength = iris[:, 2].astype('float')
volume = np.pi * petallength * (sepal_length**2)/3

# Adiciona a segunda dimensão no vetor de volume
# volume = volume[:, np.newaxis]
volume = volume.reshape(-1,1)

# Adicionando o vetor volume como coluna da matriz
out = np.hstack([iris, volume])

# View
out[:4]

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       , 38.13265163],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       , 35.20049849],
       [ 4.7       ,  3.2       ,  1.3       ,  0.2       , 30.07237208],
       [ 4.6       ,  3.1       ,  1.5       ,  0.2       , 33.23805027]])